export const propertyData = [
  {
    id: 1,
    image: `${process.env.PUBLIC_URL}/images/p1.png`,
    label: "For Rent",
    type: "Apartment",
    price: "$12,345",
    title: "Golden Urban House For Sell",
    location: "123 Street, New York, USA",
    sqft: "1000 Sqft",
    beds: "3 Bed",
    baths: "2 Bath",
  },

  {
    id: 2,
    image: `${process.env.PUBLIC_URL}/images/buy1.png`,
    label: "For Rent",
    type: "Apartment",
    price: "$12,345",
    title: "Golden Urban House For Sell",
    location: "123 Street, New York, USA",
    sqft: "1000 Sqft",
    beds: "3 Bed",
    baths: "2 Bath",
  },

  {
    id: 3,
    image: `${process.env.PUBLIC_URL}/images/buy2.png`,
    label: "For Rent",
    type: "Apartment",
    price: "$12,345",
    title: "Golden Urban House For Sell",
    location: "123 Street, New York, USA",
    sqft: "1000 Sqft",
    beds: "3 Bed",
    baths: "2 Bath",
  },

  {
    id: 4,
    image: `${process.env.PUBLIC_URL}/images/buy3.png`,
    label: "For Rent",
    type: "Apartment",
    price: "$12,345",
    title: "Golden Urban House For Sell",
    location: "123 Street, New York, USA",
    sqft: "1000 Sqft",
    beds: "3 Bed",
    baths: "2 Bath",
  },
];

export const buyData = [
  {
    id: 1,
    image: `${process.env.PUBLIC_URL}/images/buy4.png`,
    label: "Buy",
    type: "Apartment",
    price: "$12,345",
    title: "Golden Urban House For Sell",
    location: "123 Street, New York, USA",
    sqft: "1000 Sqft",
    beds: "3 Bed",
    baths: "2 Bath",
  },

  {
    id: 2,
    image: `${process.env.PUBLIC_URL}/images/buy1.png`,
    label: "Buy",
    type: "Apartment",
    price: "$12,345",
    title: "Golden Urban House For Sell",
    location: "123 Street, New York, USA",
    sqft: "1000 Sqft",
    beds: "3 Bed",
    baths: "2 Bath",
  },

  {
    id: 3,
    image: `${process.env.PUBLIC_URL}/images/buy3.png`,
    label: "Buy",
    type: "Apartment",
    price: "$12,345",
    title: "Golden Urban House For Sell",
    location: "123 Street, New York, USA",
    sqft: "1000 Sqft",
    beds: "3 Bed",
    baths: "2 Bath",
  },

  {
    id: 4,
    image: `${process.env.PUBLIC_URL}/images/buy2.png`,
    label: "Buy",
    type: "Apartment",
    price: "$12,345",
    title: "Golden Urban House For Sell",
    location: "123 Street, New York, USA",
    sqft: "1000 Sqft",
    beds: "3 Bed",
    baths: "2 Bath",
  },
];
